version: '3' # Version of the Docker Compose file format
services:
  zpublish_web:
    build:
      context: ./packages/web
      target: dev
    command: npm run dev
    environment:
      - VIRTUAL_HOST=zpublish.local
      - VIRTUAL_PORT=3000
      - NODE_ENV=development
      - NEXT_PUBLIC_APP_ENV=local
    volumes:
      - ./packages/web:/app
      - /app/node_modules
      - /app/.next
